services:
  - type: web
    name: email-kpi-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: email-kpi-redis
          property: connectionString

databases:
  - name: email-kpi-redis
    databaseName: email-kpi
    plan: free 